default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "rails_user") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "123") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "blog_app_development") %>

test:
  <<: *default
  database: blog_app_test

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME", "blog_app_production") %>
  cache:
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME", "blog_app_production") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME", "blog_app_production") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME", "blog_app_production") %>
    migrations_paths: db/cable_migrate